spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:troyka}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: troyka

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${show_sql:false}
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${show_sql:false}

server:
  port: 8080

logging:
  file:
    name: ${log_file_name:/var/log/troyka-back/application.log}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    ru.oparin.troyka: ${log_level}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}