spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?schema=${DB_SCHEMA:troyka}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 10
  sql:
    init:
      platform: postgres
  webflux:
    client:
      connect-timeout: 5000
      response-timeout: 10000


server:
  port: 8080

logging:
  file:
    name: ${log_file_name:/var/log/troyka-back/application.log}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    ru.oparin.troyka: ${log_level}
    org.springframework.r2dbc.core.DefaultDatabaseClient: ${sql_log_level:info}
    io.r2dbc.postgresql.Queries: ${sql_log_level:info}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Fal.ai API configuration
fal:
  ai:
    api:
      key: ${fal_ai_api_key:your_key_here}
      url: https://fal.run
    model: ${fal_ai_model:fal-ai/nano-banana}
    timeout: 30000